RayProfile.Web/ViewModels/SkillsViewModels.cs
namespace RayProfile.Web.ViewModels
{
    public class SkillsShowMostRequiredViewModel
    {
        public int Count { get; set; }

        public string Name { get; set; }
    }
}

RayProfile.Web/ViewModels/UserViewModels.cs
using RayProfile.Models;
using System.ComponentModel.DataAnnotations;

namespace RayProfile.Web.ViewModels
{
    public class UserBestViewModel
    {
        public double AverageVote { get; set; }

        public int Id { get; set; }

        public string Name { get; set; }

        public int VotesCount { get; set; }
    }

    public class UserEducationViewModel
    {
        public short? EndYear { get; set; }

        public string SchoolName { get; set; }

        public short StartYear { get; set; }

        public string Type { get; set; }
    }

    public class UserExperienceViewModel
    {
        public bool CompanyExists { get; set; }

        public int CompanyId { get; set; }

        public string CompanyName { get; set; }

        public short? EndYear { get; set; }

        public string Position { get; set; }

        public short StartYear { get; set; }
    }

    public class UserLoginViewModel
    {
        [Required(
            ErrorMessageResourceName = "PasswordRequired",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User)
            )]
        [Display(
            Name = "Password",
            ResourceType = typeof(Resources.ViewModels.User)
            )]
        public string Password { get; set; }

        [Required(
            ErrorMessageResourceName = "UsernameRequired",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User)
            )]
        [Display(
            Name = "Username",
            ResourceType = typeof(Resources.ViewModels.User)
            )]
        public string Username { get; set; }
    }

    public class UserRegisterViewModel
    {
        [Required(
            ErrorMessageResourceName = "EmailRequired",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User)
            )]
        [EmailAddress(
            ErrorMessage = null,
            ErrorMessageResourceName = "EmailValid",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User)
            )]
        [Display(
            Name = "Email",
            ResourceType = typeof(Resources.ViewModels.User)
            )]
        public string Email { get; set; }

        public string Message { get; set; }

        [Required(
            ErrorMessageResourceName = "PasswordRequired",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User)
            )]
        [DataType(DataType.Password)]
        [StringLength(
            150,
            MinimumLength = 4,
            ErrorMessageResourceName = "PasswordLength",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User))]
        [Display(
            Name = "Password",
            ResourceType = typeof(Resources.ViewModels.User)
            )]
        public string Password { get; set; }

        [Compare(
            "Password",
            ErrorMessageResourceName = "PasswordsMatch",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User))]
        [DataType(DataType.Password)]
        [Display(
            Name = "PasswordConfirm",
            ResourceType = typeof(Resources.ViewModels.User)
            )]
        public string PasswordConfirm { get; set; }

        [Required(
            ErrorMessageResourceName = "UsernameRequired",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User)
            )]
        [StringLength(
            150,
            MinimumLength = 4,
            ErrorMessageResourceName = "UsernameLength",
            ErrorMessageResourceType = typeof(Resources.ViewModels.User))]
        [Display(
            Name = "Username",
            ResourceType = typeof(Resources.ViewModels.User)
            )]
        public string Username { get; set; }
    }

    public class UserResourcesViewModel
    {
        public string Content { get; set; }

        public string Link { get; set; }

        public string Title { get; set; }
    }

    public class UserShowViewModel
    {
        public UserDetails Details { get; set; }

        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class UserSkillsViewModel
    {
        public int PageCount { get; set; }

        public int UserId { get; set; }
    }
}

RayProfile.Web/Controllers/SkillsController.cs
using RayProfile.Service;
using RayProfile.Web.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace RayProfile.Web.Controllers
{
    public class SkillsController : BaseController
    {
        public SkillsController()
            : base()
        {
        }

        public SkillsController(ISkillService skillService)
        {
            this.skills = skillService;
        }

        [Route("most-required-in-positions")]
        public ActionResult ShowMostRequired()
        {
            var skills = this.skills.MostUsedInPositions();
            var viewModel = new List<SkillsShowMostRequiredViewModel>();
            foreach (var item in skills)
            {
                viewModel.Add(new SkillsShowMostRequiredViewModel
                {
                    Name = item.Name,
                    Count = item.OfferSkills.Count,
                });
            }
            return PartialView(viewModel);
        }
    }
}

RayProfile.Web/Controllers/UserController.cs
using RayProfile.Models;
using RayProfile.Service;
using RayProfile.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace RayProfile.Web.Controllers
{
    public class UserController : BaseController
    {
        public UserController()
            : base()
        {
        }

        public UserController(IUserService userService, IEducationService educationService, IExperienceService experienceService, IResourceService resourceService, ISkillService skillService)
        {
            this.users = userService;
            this.education = educationService;
            this.experience = experienceService;
            this.resources = resourceService;
            this.skills = skillService;
        }

        [Route("user/best")]
        public ActionResult Best()
        {
            var users = this.users.GetBest();
            var viewModel = new List<UserBestViewModel>();
            foreach (var item in users)
            {
                var values = item.UserVotes.Select(x => x.Value).ToList();
                if (values.Count > 0)
                {
                    viewModel.Add(new UserBestViewModel
                    {
                        AverageVote = values.Average(),
                        Id = item.Id,
                        Name = item.Username,
                        VotesCount = values.Count
                    });
                }
            }
            return PartialView(viewModel);
        }

        [Route("education")]
        public ActionResult Education(int userId)
        {
            var education = this.education.GetByUserIdOrderByDesc(userId);
            var viewModel = new List<UserEducationViewModel>();
            foreach (var item in education)
            {
                viewModel.Add(new UserEducationViewModel
                {
                    EndYear = item.EndYear,
                    SchoolName = item.SchoolName,
                    StartYear = item.StartYear,
                    Type = this.education.GetEducationType(item.Type),
                });
            }
            return PartialView(viewModel);
        }

        [Route("experience")]
        public ActionResult Experience(int userId)
        {
            var experience = this.experience.GetForUser(userId);
            var viewModel = new List<UserExperienceViewModel>();
            foreach (var item in experience)
            {
                viewModel.Add(new UserExperienceViewModel
                {
                    CompanyExists = this.companies.ExistsByName(item.CompanyName),
                    CompanyName = item.CompanyName,
                    EndYear = item.EndYear,
                    Position = item.Position,
                    StartYear = item.StartYear,
                });
            }
            foreach (var item in viewModel)
            {
                if (item.CompanyExists)
                {
                    item.CompanyId = this.companies.GetByName(item.CompanyName).Id;
                }
            }
            return PartialView(viewModel);
        }

        [Route("login/user")]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [Route("login/user")]
        [HttpPost]
        public ActionResult Login(UserLoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Username = viewModel.Username.Trim();
                viewModel.Password = viewModel.Password.Trim();
                if (!this.users.UserExists(viewModel.Username))
                {
                    ModelState.AddModelError("", RayProfile.Resources.Controllers.User.UserDoesNotExists);
                }
                if (ModelState.IsValid)
                {
                    var user = this.users.GetByName(viewModel.Username);
                    if (!Crypto.VerifyHashedPassword(user.Password, viewModel.Password))
                    {
                        ModelState.AddModelError("", RayProfile.Resources.Controllers.User.UserDoesNotExists);
                    }
                    if (ModelState.IsValid)
                    {
                        FormsAuthentication.SetAuthCookie(viewModel.Username, false);
                        Session["type"] = "user";
                        return Redirect("/");
                    }
                    return View(viewModel);
                }
                return View(viewModel);
            }
            return View(viewModel);
        }

        [Route("logout")]
        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session["type"] = null;
            return Redirect("/");
        }

        [Route("register/user")]
        [HttpGet]
        public ActionResult Register()
        {
            var viewModel = new UserRegisterViewModel
            {
                Message = ""
            };
            return View(viewModel);
        }

        [Route("register/user")]
        [HttpPost]
        public ActionResult Register(UserRegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Username = viewModel.Username.Trim();
                viewModel.Email = viewModel.Email.Trim();
                viewModel.Password = viewModel.Password.Trim();
                viewModel.PasswordConfirm = viewModel.PasswordConfirm.Trim();
                if (this.users.UserOrEmailExists(viewModel.Username, viewModel.Email))
                {
                    ModelState.AddModelError("", RayProfile.Resources.Controllers.User.UserOrEmailExists);
                    return View(viewModel);
                }
                var password = viewModel.Password;

                this.users.Register(new RayProfile.Models.User
                {
                    Username = viewModel.Username,
                    Password = Crypto.HashPassword(password),
                    Email = viewModel.Email,
                    Details = new UserDetails(),
                });
                viewModel.Message = RayProfile.Resources.Controllers.User.RegisteredSuccessfully;
                return View(viewModel);
            }
            viewModel.Message = "";
            return View(viewModel);
        }

        [Route("resources")]
        public ActionResult Resources(int userId)
        {
            var resources = this.resources.GetForUser(userId);
            var viewModel = new List<UserResourcesViewModel>();
            foreach (var item in resources)
            {
                viewModel.Add(new UserResourcesViewModel
                {
                    Content = item.Content,
                    Link = item.Link,
                    Title = item.Title
                });
            }
            return PartialView(viewModel);
        }

        [Route("user/{id}")]
        [HttpGet]
        public ActionResult Show(int id)
        {
            var user = this.users.GetById(id);
            var viewModel = new UserShowViewModel
            {
                Id = user.Id,
                Name = user.Username,
                Details = user.Details
            };
            return View(viewModel);
        }

        [Route("skills")]
        public ActionResult Skills(int userId)
        {
            var skillsCount = this.skills.GetByUserId(userId).Count;
            var viewModel = new UserSkillsViewModel
            {
                PageCount = (int)Math.Ceiling((double)skillsCount / 4),
                UserId = userId,
            };
            return PartialView(viewModel);
        }
    }
}

RayProfile.Web/Controllers/VotesController.cs
using RayProfile.Service;
using RayProfile.Web.Filters;
using RayProfile.Web.ViewModels;
using System.Web.Mvc;

namespace RayProfile.Web.Controllers
{
    public class VotesController : BaseController
    {
        public VotesController()
            : base()
        {
        }

        public VotesController(IVoteService voteService)
        {
            this.votes = voteService;
        }

        [Route("company/vote/{companyId}")]
        [HttpPost]
        [IsUser]
        public ActionResult VoteCompany(int companyId, int value)
        {
            this.votes.VoteCompany(companyId, CurrentUser.Id, value);
            return Redirect("/");
        }

        [Route("company/vote")]
        [IsUser]
        public ActionResult VoteCompanyView(int companyId)
        {
            var viewModel = new VotesVoteCompanyViewViewModel();
            viewModel.CompanyId = companyId;
            if (CurrentUser != null)
                if (this.votes.UserVotedCompany(CurrentUser.Id, companyId))
                {
                    viewModel.Voted = true;
                    viewModel.Value = this.votes.GetCompanyVote(CurrentUser.Id, companyId).Value;
                }
                else
                {
                    viewModel.Voted = false;
                }
            return PartialView(viewModel);
        }

        [Route("user/vote/{userId}")]
        [HttpPost]
        [IsCompany]
        public ActionResult VoteUser(int userId, int value)
        {
            this.votes.VoteUser(userId, CurrentCompany.Id, value);
            return Redirect("/");
        }

        [Route("user/vote")]
        [IsCompany]
        public ActionResult VoteUserView(int userId)
        {
            var viewModel = new VotesVoteUserViewViewModel();
            viewModel.UserId = userId;
            if (CurrentCompany != null)
                if (this.votes.CompanyVotedUser(CurrentCompany.Id, userId))
                {
                    viewModel.Voted = true;
                    viewModel.Value = this.votes.GetUserVote(CurrentCompany.Id, userId).Value;
                }
                else
                {
                    viewModel.Voted = false;
                }
            return PartialView(viewModel);
        }
    }
}

RayProfile.Web/Views/User/Best.cshtml
@model List<RayProfile.Web.ViewModels.UserBestViewModel>

<h3>@Html.Raw(RayProfile.Resources.Common.UsersWithHighestRate)</h3>
<ol type="1" class="">
    @foreach (var item in Model)
    {
        <li><a href="/user/@item.Id">@item.Name</a> - @Math.Round(item.AverageVote, 2) (@item.VotesCount)</li>
    }
</ol>

RayProfile.Web/Views/User/Education.cshtml
@model List<RayProfile.Web.ViewModels.UserEducationViewModel>

<ul class="unstyled z-padding">
    @foreach (var item in Model)
    {
        <li>
            <div class="panel panel-default">
                <div class="panel-body">
                    <header>
                        <h4>
                            @item.SchoolName
                        </h4>
                        <h5>
                            @item.Type
                        </h5>
                    </header>
                    @item.StartYear -
                    @if (item.EndYear == null)
                    {
                        @RayProfile.Resources.Common.AtTheMoment
                    }
                    else
                    {
                        @item.EndYear
                    }
                </div>
            </div>
        </li>
    }
</ul>

RayProfile.Web/Views/User/Experience.cshtml
@model List<RayProfile.Web.ViewModels.UserExperienceViewModel>

<ul class="unstyled z-padding">
    @foreach (var item in Model)
    {
        <li>
            <div class="panel panel-default">
                <div class="panel-body">
                    <header>
                        <h4>
                            @if (!item.CompanyExists)
                            {
                                @item.CompanyName
                            }
                            else
                            {
                                <a href="/company/@item.CompanyId">@item.CompanyName</a>
                            }
                        </h4>
                        <h5>
                            @item.Position
                        </h5>
                    </header>
                    @item.StartYear -
                    @if (item.EndYear == null)
                    {
                        <span>@RayProfile.Resources.Common.AtTheMoment</span>
                    }
                    else
                    {
                        @item.EndYear
                    }
                </div>
            </div>
        </li>
    }
</ul>

RayProfile.Web/Views/User/Login.cshtml
@model RayProfile.Web.ViewModels.UserLoginViewModel

@{
    ViewBag.Title = RayProfile.Resources.Common.Login;
}

<h2>@RayProfile.Resources.Common.Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username)
                @Html.ValidationMessageFor(model => model.Username, "*")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password, "*")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@RayProfile.Resources.Common.Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RayProfile.Web/Views/User/Register.cshtml
@model RayProfile.Web.ViewModels.UserRegisterViewModel

@{
    ViewBag.Title = RayProfile.Resources.Common.Register;
}

<h2>@RayProfile.Resources.Common.Register</h2>

@if (Model.Message != String.Empty)
{
    <div class="alert alert-success">
        @Model.Message
    </div>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username)
                @Html.ValidationMessageFor(model => model.Username, "*")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password, "*")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordConfirm, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.PasswordConfirm)
                @Html.ValidationMessageFor(model => model.PasswordConfirm, "*")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email, "*")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@RayProfile.Resources.Common.Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RayProfile.Web/Views/User/Resources.cshtml
@model List<RayProfile.Web.ViewModels.UserResourcesViewModel>

<ul class="unstyled z-padding">
    @foreach (var item in Model)
    {
        <li>
            <div class="panel panel-default">
                <header class="panel-heading">
                    <h3>@item.Title</h3>
                </header>
                <div class="panel-body">

                    @if (item.Content != null)
                    {
                        <p>@item.Content</p>
                    }
                    @if (item.Link != null)
                    {
                        <p><a href="@item.Link">@item.Link</a></p>
                    }
                </div>
            </div>
        </li>
    }
</ul>

RayProfile.Web/Views/User/Show.cshtml
@model RayProfile.Web.ViewModels.UserShowViewModel

@{
    ViewBag.Title = Model.Name;
}
<h3>@Model.Name</h3>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-md-6">
            @if (Model.Details.FirstName != null)
            {
                <div>
                    @RayProfile.Resources.Views.User.FirstName: @Model.Details.FirstName
                </div>
            }
            @if (Model.Details.FatherName != null)
            {
                <div>
                    @RayProfile.Resources.Views.User.FatherName: @Model.Details.FatherName
                </div>
            }
            @if (Model.Details.Surname != null)
            {
                <div>
                    @RayProfile.Resources.Views.User.Surname: @Model.Details.Surname
                </div>
            }
            @if (Model.Details.Sex != 0 && Model.Details.Sex != null)
            {
                <div>
                    @RayProfile.Resources.Views.User.Sex:
                    @if (Model.Details.Sex == 1)
                    {
                        <span>@RayProfile.Resources.Views.User.Male</span>
                    }
                    else
                    {
                        <span>@RayProfile.Resources.Views.User.Female   </span>
                    }
                </div>
            }
            @if (Model.Details.Country != null)
            {
                <div>
                    @RayProfile.Resources.Views.User.Country: @Model.Details.Country
                </div>
            }
            @if (Model.Details.Town != null)
            {
                <div>
                    @RayProfile.Resources.Views.User.Town: @Model.Details.Town
                </div>
            }
        </div>
        @if (Model.Details.About != null)
        {
            <div class="col-md-4">
                <div>
                    @RayProfile.Resources.Views.User.About: @Model.Details.About
                </div>
            </div>
        }

        @if (User.Identity.IsAuthenticated && Session["type"] != null && Session["type"].ToString() == "company")
        {
            <div class="col-md-3">
                @Html.Action("VoteUserView", "Votes", new { userId = Model.Id })
            </div>
        }
    </div>
</div>
<div>
    <div class="tab-nav nav navbar-default">
        <ul class="nav navbar-nav">
            <li><a href="#skills" data-toggle="tab">@RayProfile.Resources.Common.Skills</a></li>
            <li><a href="#experience" data-toggle="tab">@RayProfile.Resources.Common.Experience</a></li>
            <li><a href="#education" data-toggle="tab">@RayProfile.Resources.Common.Education</a></li>
            <li><a href="#resources" data-toggle="tab">@RayProfile.Resources.Common.Resources</a></li>
        </ul>
    </div>
    <div class="tab-content">
        <div class="user-show-container container tab-pane active" id="skills">
            @Html.Action("Skills", "User", new { userId = Model.Id })
        </div>
        <div class="user-show-container container tab-pane z-padding" id="experience">
            @Html.Action("Experience", "User", new { userId = Model.Id })
        </div>
        <div class="user-show-container container tab-pane z-padding" id="resources">
            @Html.Action("Resources", "User", new { userId = Model.Id })
        </div>
        <div class="user-show-container container tab-pane z-padding" id="education">
            @Html.Action("Education", "User", new { userId = Model.Id })
        </div>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/Scripts/skills.js")
}

RayProfile.Web/Views/User/Skills.cshtml
@model RayProfile.Web.ViewModels.UserSkillsViewModel

<input type="hidden" name="userId" value="@Model.UserId" />
<div class="skillrow row">
</div>
<div>
    <ul class="pagination">
        @for (int i = 1; i <= Model.PageCount; i++)
        {
            <li><a class="page-button" href="javascript:;" data-page="@i">@i</a></li>
        }
    </ul>
</div>