RayProfile.Web/Controllers/CompanyController.cs
using RayProfile.Models;
using RayProfile.Service;
using RayProfile.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace RayProfile.Web.Controllers
{
    public class CompanyController : BaseController
    {
        public CompanyController()
            : base()
        {
        }

        public CompanyController(ICompanyService companyService, IPositionService positionService, IProductService productService)
        {
            this.companies = companyService;
            this.positions = positionService;
            this.products = productService;
        }

        [Route("company/best")]
        public ActionResult Best()
        {
            var companies = this.companies.GetBest();
            var viewModel = new List<CompanyBestViewModel>();
            foreach (var item in companies)
            {
                var values = item.CompanyVotes.Select(x => x.Value).ToList();
                viewModel.Add(new CompanyBestViewModel
                {
                    AverageVote = values.Average(),
                    Id = item.Id,
                    Name = item.Name,
                    VotesCount = values.Count
                });
            }
            return PartialView(viewModel);
        }

        [Route("login/company")]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [Route("login/company")]
        [HttpPost]
        public ActionResult Login(CompanyLoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.LoginName = viewModel.LoginName.Trim();
                viewModel.Password = viewModel.Password.Trim();
                if (
                    !this.companies.Exists(viewModel.LoginName) ||
                    !Crypto.VerifyHashedPassword(
                    this.companies.GetByLoginName(viewModel.LoginName).Password,
                    viewModel.Password)
                    )
                {
                    ModelState.AddModelError("", Resources.Controllers.Company.CompanyNotExists);
                }
                if (ModelState.IsValid)
                {
                    FormsAuthentication.SetAuthCookie(viewModel.LoginName, false);
                    Session["type"] = "company";
                    return Redirect("/");
                }
                return View(viewModel);
            }
            return View(viewModel);
        }

        [Route("positions")]
        public ActionResult Positions(int companyId)
        {
            var positions = this.positions.GetForCompany(companyId);
            var viewModel = new List<CompanyPositionsViewModel>();
            foreach (var item in positions)
            {
                var skills = new List<PositionSkillModel>();
                Models.User user = CurrentUser;

                foreach (var skill in item.Skills)
                {
                    skills.Add(new PositionSkillModel
                    {
                        Name = skill.Skill.Name,
                        Value = skill.Value,
                    });
                }
                viewModel.Add(new CompanyPositionsViewModel
                {
                    Id = item.Id,
                    CurrentUser = user,
                    Desc = item.Desc,
                    Name = item.Name,
                    Skills = skills,
                });
            }
            return PartialView(viewModel);
        }

        [Route("products")]
        public ActionResult Products(int companyId)
        {
            var products = this.products.GetForCompany(companyId);
            var viewModel = new List<CompanyProductsViewModel>();
            foreach (var item in products)
            {
                viewModel.Add(new CompanyProductsViewModel
                {
                    Name = item.Name,
                    Desc = item.Desc,
                });
            }
            return PartialView(viewModel);
        }

        [Route("register/company")]
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [Route("register/company")]
        [HttpPost]
        public ActionResult Register(CompanyRegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Email = viewModel.Email.Trim();
                viewModel.LoginName = viewModel.LoginName.Trim();
                viewModel.Name = viewModel.Name.Trim();
                viewModel.Password = viewModel.Password.Trim();
                if (this.companies.CompanyLoginOrNameOrEmailExists(viewModel.LoginName, viewModel.Name, viewModel.Email))
                {
                    ModelState.AddModelError("", Resources.Controllers.Company.CompanyExists);
                }
                if (ModelState.IsValid)
                {
                    this.companies.Register(new Company
                    {
                        Email = viewModel.Email,
                        LoginName = viewModel.LoginName,
                        Name = viewModel.Name,
                        Password = Crypto.HashPassword(viewModel.Password),
                        Details = new CompanyDetails(),
                    });
                    FormsAuthentication.SetAuthCookie(viewModel.LoginName, false);
                    Session["type"] = "company";
                    return Redirect("/");
                }
                return View(viewModel);
            }
            return View(viewModel);
        }

        [Route("company/{id}")]
        [HttpGet]
        public ActionResult Show(int id)
        {
            var company = this.companies.GetById(id);
            var viewModel = new CompanyShowViewModel
            {
                Id = company.Id,
                Name = company.Name,
                Desc = company.Details.Desc,
                Founded = company.Details.Founded,
                Industry = company.Details.Industry,
                Site = company.Details.Site,
                Size = this.companyDetails.CompanySizeToString(company.Details.Size),
            };
            return View(viewModel);
        }
    }
}

RayProfile.Web/Controllers/SkillsController.cs
using RayProfile.Service;
using RayProfile.Web.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace RayProfile.Web.Controllers
{
    public class SkillsController : BaseController
    {
        public SkillsController()
            : base()
        {
        }

        public SkillsController(ISkillService skillService)
        {
            this.skills = skillService;
        }

        [Route("most-required-in-positions")]
        public ActionResult ShowMostRequired()
        {
            var skills = this.skills.MostUsedInPositions();
            var viewModel = new List<SkillsShowMostRequiredViewModel>();
            foreach (var item in skills)
            {
                viewModel.Add(new SkillsShowMostRequiredViewModel
                {
                    Name = item.Name,
                    Count = item.OfferSkills.Count,
                });
            }
            return PartialView(viewModel);
        }
    }
}

RayProfile.Web/Controllers/UserController.cs
using RayProfile.Models;
using RayProfile.Service;
using RayProfile.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace RayProfile.Web.Controllers
{
    public class UserController : BaseController
    {
        public UserController()
            : base()
        {
        }

        public UserController(IUserService userService, IEducationService educationService, IExperienceService experienceService, IResourceService resourceService, ISkillService skillService)
        {
            this.users = userService;
            this.education = educationService;
            this.experience = experienceService;
            this.resources = resourceService;
            this.skills = skillService;
        }

        [Route("user/best")]
        public ActionResult Best()
        {
            var users = this.users.GetBest();
            var viewModel = new List<UserBestViewModel>();
            foreach (var item in users)
            {
                var values = item.UserVotes.Select(x => x.Value).ToList();
                if (values.Count > 0)
                {
                    viewModel.Add(new UserBestViewModel
                    {
                        AverageVote = values.Average(),
                        Id = item.Id,
                        Name = item.Username,
                        VotesCount = values.Count
                    });
                }
            }
            return PartialView(viewModel);
        }

        [Route("education")]
        public ActionResult Education(int userId)
        {
            var education = this.education.GetByUserIdOrderByDesc(userId);
            var viewModel = new List<UserEducationViewModel>();
            foreach (var item in education)
            {
                viewModel.Add(new UserEducationViewModel
                {
                    EndYear = item.EndYear,
                    SchoolName = item.SchoolName,
                    StartYear = item.StartYear,
                    Type = this.education.GetEducationType(item.Type),
                });
            }
            return PartialView(viewModel);
        }

        [Route("experience")]
        public ActionResult Experience(int userId)
        {
            var experience = this.experience.GetForUser(userId);
            var viewModel = new List<UserExperienceViewModel>();
            foreach (var item in experience)
            {
                viewModel.Add(new UserExperienceViewModel
                {
                    CompanyExists = this.companies.ExistsByName(item.CompanyName),
                    CompanyName = item.CompanyName,
                    EndYear = item.EndYear,
                    Position = item.Position,
                    StartYear = item.StartYear,
                });
            }
            foreach (var item in viewModel)
            {
                if (item.CompanyExists)
                {
                    item.CompanyId = this.companies.GetByName(item.CompanyName).Id;
                }
            }
            return PartialView(viewModel);
        }

        [Route("login/user")]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [Route("login/user")]
        [HttpPost]
        public ActionResult Login(UserLoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Username = viewModel.Username.Trim();
                viewModel.Password = viewModel.Password.Trim();
                if (!this.users.UserExists(viewModel.Username))
                {
                    ModelState.AddModelError("", RayProfile.Resources.Controllers.User.UserDoesNotExists);
                }
                if (ModelState.IsValid)
                {
                    var user = this.users.GetByName(viewModel.Username);
                    if (!Crypto.VerifyHashedPassword(user.Password, viewModel.Password))
                    {
                        ModelState.AddModelError("", RayProfile.Resources.Controllers.User.UserDoesNotExists);
                    }
                    if (ModelState.IsValid)
                    {
                        FormsAuthentication.SetAuthCookie(viewModel.Username, false);
                        Session["type"] = "user";
                        return Redirect("/");
                    }
                    return View(viewModel);
                }
                return View(viewModel);
            }
            return View(viewModel);
        }

        [Route("logout")]
        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session["type"] = null;
            return Redirect("/");
        }

        [Route("register/user")]
        [HttpGet]
        public ActionResult Register()
        {
            var viewModel = new UserRegisterViewModel
            {
                Message = ""
            };
            return View(viewModel);
        }

        [Route("register/user")]
        [HttpPost]
        public ActionResult Register(UserRegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Username = viewModel.Username.Trim();
                viewModel.Email = viewModel.Email.Trim();
                viewModel.Password = viewModel.Password.Trim();
                viewModel.PasswordConfirm = viewModel.PasswordConfirm.Trim();
                if (this.users.UserOrEmailExists(viewModel.Username, viewModel.Email))
                {
                    ModelState.AddModelError("", RayProfile.Resources.Controllers.User.UserOrEmailExists);
                    return View(viewModel);
                }
                var password = viewModel.Password;

                this.users.Register(new RayProfile.Models.User
                {
                    Username = viewModel.Username,
                    Password = Crypto.HashPassword(password),
                    Email = viewModel.Email,
                    Details = new UserDetails(),
                });
                viewModel.Message = RayProfile.Resources.Controllers.User.RegisteredSuccessfully;
                return View(viewModel);
            }
            viewModel.Message = "";
            return View(viewModel);
        }

        [Route("resources")]
        public ActionResult Resources(int userId)
        {
            var resources = this.resources.GetForUser(userId);
            var viewModel = new List<UserResourcesViewModel>();
            foreach (var item in resources)
            {
                viewModel.Add(new UserResourcesViewModel
                {
                    Content = item.Content,
                    Link = item.Link,
                    Title = item.Title
                });
            }
            return PartialView(viewModel);
        }

        [Route("user/{id}")]
        [HttpGet]
        public ActionResult Show(int id)
        {
            var user = this.users.GetById(id);
            var viewModel = new UserShowViewModel
            {
                Id = user.Id,
                Name = user.Username,
                Details = user.Details
            };
            return View(viewModel);
        }

        [Route("skills")]
        public ActionResult Skills(int userId)
        {
            var skillsCount = this.skills.GetByUserId(userId).Count;
            var viewModel = new UserSkillsViewModel
            {
                PageCount = (int)Math.Ceiling((double)skillsCount / 4),
                UserId = userId,
            };
            return PartialView(viewModel);
        }
    }
}

RayProfile.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RayProfile</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">RayProfile</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (Session["type"].ToString() == "user")
                        {
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                                    @RayProfile.Resources.Common.Profile <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/user/details">
                                            @RayProfile.Resources.Common.Details
                                        </a>
                                        <a href="/user/skills">
                                            @RayProfile.Resources.Common.Skills
                                        </a>
                                        <a href="/user/experience">
                                            @RayProfile.Resources.Common.Experience
                                        </a>
                                        <a href="/user/resources">
                                            @RayProfile.Resources.Common.Resources
                                        </a>
                                        <a href="/user/education">
                                            @RayProfile.Resources.Common.Education
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="/user/messages">@RayProfile.Resources.Common.Messages</a>
                            </li>
                        }
                        else if (Session["type"].ToString() == "company")
                        {
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                                    @RayProfile.Resources.Common.Company <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/company/details">
                                            @RayProfile.Resources.Common.Details
                                        </a>
                                        <a href="/company/products">
                                            @RayProfile.Resources.Common.ProductsAndServices
                                        </a>
                                        <a href="/company/positions">
                                            @RayProfile.Resources.Common.Positions
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/lang/bg?returnUrl=@Request.Path">
                            <img width="30" height="" alt="bg" src="/Content/bg.png" />
                        </a>
                    </li>
                    <li>
                        <a href="/lang/en?returnUrl=@Request.Path">
                            <img width="" height="" alt="en" src="/Content/en.png" />
                        </a>
                    </li>
                    <li style="padding-top: 6px">
                        <form action="/search" method="get" class="form-inline">
                            <div class="form-group">
                                <input class="form-control" type="text" name="q" placeholder="@RayProfile.Resources.Common.SearchCompanyOrUser" />
                            </div>
                            <div class="form-group">
                                <input value="@RayProfile.Resources.Common.Search" type="submit" class="btn btn-default btn-sm" />
                            </div>
                        </form>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="javascript:;">@RayProfile.Resources.Common.Hello @User.Identity.Name</a>
                        </li>
                        <li>
                            <a href="/logout">@RayProfile.Resources.Common.Logout</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="javascript:;">
                                @RayProfile.Resources.Common.Register<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/register/user">@RayProfile.Resources.Common.AsUser</a>
                                </li>
                                <li>
                                    <a href="/register/company">@RayProfile.Resources.Common.AsCompany</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="javascript:;">
                                @RayProfile.Resources.Common.Login<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/login/user">@RayProfile.Resources.Common.AsUser</a>
                                </li>
                                <li>
                                    <a href="/login/company">@RayProfile.Resources.Common.AsCompany</a>
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="hidden-sm hidden-xs col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li style="width: 33%;" class="active"><a style="white-space: normal;" href="#most-required" data-toggle="tab">@Html.Raw(RayProfile.Resources.Common.MostRequiredSkills)</a></li>
                            <li style="width: 33%;"><a style="white-space: normal;" href="#best-companies" data-toggle="tab">@Html.Raw(RayProfile.Resources.Common.CompaniesWithHighestRate)</a></li>
                            <li style="width: 33%;"><a style="white-space: normal;" href="#best-users" data-toggle="tab">@Html.Raw(RayProfile.Resources.Common.UsersWithHighestRate)</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="user-show-container container tab-pane active" id="most-required">
                                @Html.Action("ShowMostRequired", "Skills")
                            </div>
                            <div class="user-show-container z-padding container tab-pane" id="best-companies">
                                @Html.Action("Best", "Company")
                            </div>
                            <div class="user-show-container z-padding container tab-pane" id="best-users">
                                @Html.Action("Best", "User")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RayProfile</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/underscore.min.js")
    @RenderSection("scripts", required: false)
    <script>
    </script>
</body>
</html>